### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by nightmareeye** [nightmareeye/todo-lr1#3]
### Todo:

- [x] создать коллекцию
- [x] через переменные окружения настроить URL
- [x] реализовать все запросы
- [x] экспортировать запросы и сохранить в своём проекте
