### ISSUE TITLE
Fixing bugs

### ISSUE THREAD

**Issue by nightmareeye** [nightmareeye/todo-lr1#5]
### Todo:

- [x] Падение при создании пустой задачи. Реализовать с помощью status_code
- [x] Падение при удалении несуществующей задачи
- [x] Добавить ограничение на длину загружаемой записи в 500 символов
- [x] Есть ли ещё?
